['Ik ga U over ... minuten meer uitleggen.',
 'Ik ga U om *tijdstip* meer uitleggen.',
 'De arts gaat U over ... minuten meer uitleggen.',
 'De arts gaat U om *tijdstip* meer uitleggen.',
 'Mijn collega gaat U over ... minuten meer uitleggen.',
 'Mijn collega gaat U om *tijdstip* meer uitleggen.',
 'De leverwaardes zijn te hoog.',
 'De leverwaardes zijn te laag.',
 'De nierwaardes zijn te hoog.',
 'De nierwaardes zijn te laag.',
 'De infectiewaardes zijn te hoog.',
 'De infectiewaardes te laag.',
 'De bloedwaardes zijn te hoog.',
 'De bloedwaardes zijn te laag.',
 'De zuurstofwaardes zijn te hoog.',
 'De zuurstofwaardes te laag.',
 'De hartwaardes zijn te hoog.',
 'De hartwaardes te laag.',
 'De schildklierwaardes zijn te hoog.',
 'De schildklierwaardes te laag.',
 'U krijgt andere medicijnen. Dit zijn medicijnen via infuus.',
 'U krijgt andere medicijnen. Dit zijn medicijnen via tabletten.',
 'U krijgt andere medicijnen. Dit zijn medicijnen via drankje.',
 'Uw meetwaardes op de monitor verbeteren.',
 'Uw meetwaardes op de monitor verslechteren.',
 'Uw bloedwaardes verbeteren.',
 'Uw bloedwaardes verslechteren.',
 'De uitslag van de COVID-19 test komt vanmiddag.',
 'De uitslag van de COVID-19 test komt morgen.',
 'De uitslag van de COVID-19 test komt morgenochtend.',
 'De uitslag van de COVID-19 test komt morgenmiddag.',
 'De uitslag van de COVID-19 test komt morgenavond.',
 'De uitslag van de COVID-19 test is vertraagd.',
 'De röntgenfoto is goed.',
 'De röntgenfoto is niet helemaal goed.',
 'De röntgenfoto is niet goed.',
 'De MRI is goed.',
 'De MRI is niet helemaal goed.',
 'De MRI is hetzelfde gebleven.',
 'De MRI is verbeterd.',
 'De MRI is is verslechterd.',
 'De MRI is niet goed.',
 'De scintigrafie (vingerspellen) is goed.',
 'De scintigrafie (vingerspellen) is niet helemaal goed.',
 'De scintigrafie (vingerspellen) is hetzelfde gebleven.',
 'De scintigrafie (vingerspellen) is verbeterd.',
 'De scintigrafie (vingerspellen) is is verslechterd.',
 'De scintigrafie (vingerspellen) is niet goed.',
 'De echo is goed.',
 'De echo is niet helemaal goed.',
 'De echo is hetzelfde gebleven.',
 'De echo is verbeterd.',
 'De echo is is verslechterd.',
 'De echo is niet goed.',
 'De bloedkweek is goed.',
 'De bloedkweek is niet helemaal goed.',
 'De bloedkweek is hetzelfde gebleven.',
 'De bloedkweek is verbeterd.',
 'De bloedkweek is is verslechterd.',
 'De bloedkweek is niet goed.',
 'De botscan; officiële naam dexascan (vingerspellen) is goed.',
 'De botscan; officiële naam dexascan (vingerspellen) is niet helemaal goed.',
 'De botscan; officiële naam dexascan (vingerspellen) is hetzelfde gebleven.',
 'De botscan; officiële naam dexascan (vingerspellen) is verbeterd.',
 'De botscan; officiële naam dexascan (vingerspellen) is is verslechterd.',
 'De botscan; officiële naam dexascan (vingerspellen) is niet goed.',
 'Uw bloeddruk is … over…',
 'Ik kom het infuus controleren (of het nog goed loopt).',
 'Er gebeuren vandaag geen onderzoeken of gesprekken meer.',
 'Tablet',
 'Drankje',
 'Druppels',
 'Zalf',
 'Injectie/ prik',
 'Infuus',
 'Bloedprikken (bloed afnemen)',
 'Recept voor medicijnen',
 'Ziekenhuis',
 'Polikliniek',
 'Huisarts',
 'Apotheek',
 'Afdeling',
 'Eerste hulp',
 'Intensive care',
 'Revalidatie',
 'Intensivist',
 'Arts van de intensive care afdeling',
 'Internist',
 'Zaalarts',
 'Longarts',
 'Cardioloog',
 'Dermatoloog',
 'Neuroloog',
 'Radioloog',
 'Psycholoog',
 'Psychiater',
 'Anesthesist',
 'Onderzoek',
 'Uitslag',
 'Bloedonderzoek',
 'Bloeddruk',
 'Hoog',
 'Laag',
 'Normaal',
 'Normaal ademen',
 'Diep in en uit ademen',
 'Echo',
 'CT-scan',
 'MRI-scan',
 'Röntgenfoto',
 'Pijn',
 'Bacterie',
 'Virus',
 'Verpleegkundige',
 'Arts',
 'Narcose',
 'Catheter',
 'Plassen',
 'Poepen',
 'WC',
 'Koorts',
 'Longen',
 'Hart',
 'Lever',
 'Nieren',
 'Maag',
 'Schildklier',
 'Alvleesklier',
 'Blaas',
 'Darmen',
 'Galblaas',
 'Hersenen',
 '1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,20,25,45 minuten',
 'Half uur',
 'Drie kwartier',
 '(1,2,3 ...) Uur',
 'Tussen .. en .. uur.',
 'Vanmiddag',
 'Vanavond',
 'Morgen',
 'Morgenochtend',
 'Morgenmiddag',
 'Morgenavond',
 'Overmorgen',
 '(2,3,4 ...) dagen',
 '1 week',
 '(2,3,4 ...) weken',
 '1 maand',
 '(2,3,4 ...) maanden',
 'Om ongeveer *tijdstip* komt de arts.',
 'Om ongeveer *tijdstip* komt de fysiotherapeut.',
 'Om ongeveer *tijdstip* kom ik terug.',
 'Om ongeveer *tijdstip* komt eten.',
 'Om ongeveer *tijdstip* is de CT-scan.',
 'Om ongeveer *tijdstip* is de MRI-scan.',
 'Om ongeveer *tijdstip* is de röntgenfoto.',
 'Om ongeveer *tijdstip* mag U naar huis.',
 'Om ongeveer *tijdstip* gaat U naar een andere afdeling.',
 'Om ongeveer *tijdstip* wordt bloed geprikt.',
 'We gaan elke dag bloed afnemen.',
 'We gaan om de dag bloed afnemen.',
 'We gaan op maandag, woensdag en vrijdag bloed afnemen.',
 'We gaan 1x per week bloed afnemen.',
 'We gaan 2x per week bloed afnemen.',
 'U moet nuchter blijven dus U mag niet eten tot *tijdstip*.',
 'U moet nuchter blijven dus U mag niet eten tot het onderzoek.',
 'U moet nuchter blijven dus U mag niet eten tot de operatie.',
 'Honger',
 'Dorst',
 'Tolk gebarentaal',
 'Schrijftolk']
